model:
  arch: video_llama

  # Q-Former
  num_query_token: 32


preprocess:
    vis_processor:
        train:
          name: "alpro_video_train"
          image_size: 224
          n_frms: 8
        eval:
          name: "alpro_video_eval"
          image_size: 224
          n_frms: 8
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
    